export const SITE_CONFIG = {
  name: "Mohammed Yessin Driss",
  shortName: "M. Y. Driss",
  role: "Marketing Operator & Brand Builder",
  location: "Tunis, Tunisia",
  available: true,
  linkedin: "https://www.linkedin.com/in/medyessin-driss/",
  email: "mohammedyessindriss@gmail.com",
} as const;

export const PROJECTS = [
  {
    id: "bume",
    title: "Bume.tn",
    category: "Brand Launch",
    period: "Jun–Aug 2025",
    role: "Chief Marketing Officer",
    tagline: "Built a brand from zero and drove 100 paying students in the first cohort",
    backgroundColor: "#FAFAF9",
    textColor: "#0F0F0F",
    borderColor: "#E5E7EB",
    isLight: true,
    metrics: [
      { value: "0→2,500", label: "TikTok followers" },
      { value: "90K+", label: "Video views" },
      { value: "100", label: "Paying students" },
    ],
    problem: "Launching Bume.tn from absolute zero with no budget, no audience, and no brand recognition in a crowded Tunisian education market.",
    strategy: "Built an educational content machine on TikTok and Instagram that spoke as a peer, not an institution. Webinars as conversion mechanisms. Every piece of content solved a real student anxiety.",
    retrospective: "Visual clarity and human conversation convert twice as fast as generic advertising. The first cohort was filled entirely through organic content and direct community engagement.",
  },
  {
    id: "tbs-je",
    title: "TBS Junior Enterprise",
    category: "B2B Marketing",
    period: "Jun 2025–Jul 2026",
    role: "Marketing & Communications Director",
    tagline: "Drove 717% LinkedIn impression growth and maintained ISO 9001 certification",
    backgroundColor: "#2e3785",
    textColor: "#ffffff",
    borderColor: "rgba(255,255,255,0.25)",
    isLight: false,
    metrics: [
      { value: "717%", label: "LinkedIn impression growth" },
      { value: "32,600%", label: "Reaction increase" },
      { value: "ISO 9001", label: "Certification maintained" },
    ],
    problem: "Inconsistent B2B presence failing to communicate the real caliber of the consulting firm to international clients and corporate partners.",
    strategy: "Applied ISO 9001 quality control directly to the content workflow. Rebuilt LinkedIn into a publication-grade channel for corporate decision makers.",
    retrospective: "Process frameworks are not the enemy of creativity. Instilling quality management actually speeds up creative decisions and produces the consistency B2B clients pay for.",
  },
  {
    id: "croki",
    title: "CROKI",
    category: "Growth & BD",
    period: "Jan–May 2025",
    role: "Digital Marketing & BD Intern",
    tagline: "Generated 16K+ TikTok reach and informed pricing strategy through customer research",
    backgroundColor: "#FAFAF9",
    textColor: "#0F0F0F",
    borderColor: "#E5E7EB",
    isLight: true,
    metrics: [
      { value: "16K+", label: "TikTok organic reach" },
      { value: "120+", label: "Customer interviews" },
      { value: "1", label: "Pricing strategy rebuilt" },
    ],
    problem: "Zero digital footprint and a pricing model built on intuition rather than customer data.",
    strategy: "Native TikTok content speaking the language of Tunisian students. Simultaneous customer research through 120+ interviews to rebuild pricing from real data.",
    retrospective: "To win youth attention you must speak as a classmate. And pricing without customer research is just guessing with consequences.",
  },
  {
    id: "skills4trade",
    title: "Skills4Trade",
    category: "SaaS Marketing",
    period: "Jun–Aug 2025",
    role: "Digital Marketing Associate",
    tagline: "Owned the full marketing operation of an early-stage SaaS startup independently",
    backgroundColor: "#207ca9",
    textColor: "#ffffff",
    borderColor: "rgba(255,255,255,0.25)",
    isLight: false,
    metrics: [
      { value: "100%", label: "Solo marketing operation" },
      { value: "3", label: "Channels built from zero" },
      { value: "Direct", label: "CEO coordination" },
    ],
    problem: "Advanced SaaS product with zero marketing infrastructure, zero search authority, and complete reliance on manual outreach.",
    strategy: "Built self-sustaining digital marketing systems from scratch — SEO content architecture, email funnels, social presence — all owned and executed independently.",
    retrospective: "In an early-stage startup, execution speed matters more than perfection. Build the systems first, optimize with real data second.",
  },
  {
    id: "netinfo",
    title: "Netinfo",
    category: "Community & Ads",
    period: "Apr–Jun 2025",
    role: "Community Manager",
    tagline: "Managed social presence and ran paid campaigns for a digital training center",
    backgroundColor: "#FAFAF9",
    textColor: "#0F0F0F",
    borderColor: "#E5E7EB",
    isLight: true,
    metrics: [
      { value: "<15min", label: "Average response time" },
      { value: "14+", label: "Ad campaigns run" },
      { value: "40%+", label: "Engagement increase" },
    ],
    problem: "Passive community with slow response times causing lead drop-off and underperforming paid ad campaigns.",
    strategy: "Real-time response systems, direct reply playbooks, and performance-focused ad creatives with conversion-first CTAs.",
    retrospective: "Social conversions are conversation-dependent. If a client waits more than 30 minutes for an answer, they forget your brand exists.",
  },
] as const;
