export const SITE_CONFIG = {
  name: "Mohammed Yessin Driss",
  shortName: "M. Y. Driss",
  role: "Marketing Operator & Brand Builder",
  location: "Tunis, Tunisia",
  available: true,
  linkedin: "https://www.linkedin.com/in/medyessin-driss/",
  email: "mohammedyessindriss@gmail.com",
} as const;

export const PROJECTS = [
  {
    id: "tbs-je",
    title: "TBS Junior Enterprise",
    category: "B2B Marketing",
    period: "Jun 2025–Jul 2026",
    role: "Marketing & Communications Director",
    tagline: "Drove 717% LinkedIn impression growth and maintained ISO 9001 certification",
    backgroundColor: "#FAFAF9",
    textColor: "#0F0F0F",
    borderColor: "#E5E7EB",
    isLight: true,
    metrics: [
      { value: "717%", label: "LinkedIn impression growth" },
      { value: "32,600%", label: "Reaction increase" },
      { value: "ISO 9001", label: "Certification maintained" },
    ],
  },
  {
    id: "bume",
    title: "Bume.tn",
    category: "Brand Launch",
    period: "Jun–Aug 2025",
    role: "Chief Marketing Officer",
    tagline: "Built a brand from zero and drove 100 paying students in the first cohort",
    backgroundColor: "#207ca9",
    textColor: "#ffffff",
    borderColor: "rgba(255,255,255,0.25)",
    isLight: false,
    metrics: [
      { value: "0→2,500", label: "TikTok followers" },
      { value: "90K+", label: "Video views" },
      { value: "100", label: "Paying students" },
    ],
  },
  {
    id: "croki",
    title: "CROKI",
    category: "Growth & BD",
    period: "Jan–May 2025",
    role: "Digital Marketing & BD Intern",
    tagline: "Generated 16K+ TikTok reach and informed pricing strategy through customer research",
    backgroundColor: "#FAFAF9",
    textColor: "#0F0F0F",
    borderColor: "#E5E7EB",
    isLight: true,
    metrics: [
      { value: "16K+", label: "TikTok organic reach" },
      { value: "120+", label: "Customer interviews" },
      { value: "1", label: "Pricing strategy rebuilt" },
    ],
  },
  {
    id: "skills4trade",
    title: "Skills4Trade",
    category: "SaaS Marketing",
    period: "Jun–Aug 2025",
    role: "Digital Marketing Associate",
    tagline: "Owned the full marketing operation of an early-stage SaaS startup independently",
    backgroundColor: "#207ca9",
    textColor: "#ffffff",
    borderColor: "rgba(255,255,255,0.25)",
    isLight: false,
    metrics: [
      { value: "100%", label: "Solo marketing operation" },
      { value: "3", label: "Channels built from zero" },
      { value: "Direct", label: "CEO coordination" },
    ],
  },
] as const;
